# Topic Modelling

## 1. Basic LDA Model
- Here we will consider all the words for LDA model

In [1]:
# import 
import pandas as pd
import pickle

data = pd.read_pickle("bow_2.pkl")

In [2]:
data

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,...,zee,zen,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,Ã©clair
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,1,1,1,1,0,0
bo,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,2,1,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,3,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0

In [3]:
# import LDA packages
from gensim import matutils, models
import scipy.sparse

In [4]:
# transpose document term matrix into a term document matrix and feed it to gensim
tdm = data.transpose()
tdm.head()

,ali,anthony,bill,bo,dave,hasan,jim,joe,john,louis,mike,ricky
aaaaah,0,0,1,0,0,0,0,0,0,0,0,0
aaaaahhhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaaauuugghhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaahhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaah,0,0,0,0,1,0,0,0,0,0,0,0

In [5]:
# df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [6]:
# Gensim also requires dictionary of the all terms 
# and their respective location in the term-document matrix
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v,k) for k, v in cv.vocabulary_.items())

In [7]:
len(id2word)

7296

Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term), we need to specify two other parameters 
- the number of topics and 
- the number of passes. 

Let's start the number of topics at 2, see if the results make sense, and increase the number from there.

In [8]:
# LDA model for 2 topics & 10 passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.007*"shit" + 0.005*"life" + 0.005*"cause" + 0.005*"ok" + 0.004*"thing" + 0.004*"lot" + 0.004*"women" + 0.004*"really" + 0.003*"gotta" + 0.003*"day"'),
 (1,
  '0.009*"fucking" + 0.006*"fuck" + 0.006*"shit" + 0.006*"going" + 0.005*"want" + 0.005*"day" + 0.005*"went" + 0.005*"good" + 0.004*"thing" + 0.004*"little"')]

- this is not giving enough insights
- let's create a model with 3 topics

In [9]:
# LDA model for 3 topics & 10 passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.011*"shit" + 0.010*"fucking" + 0.007*"fuck" + 0.005*"want" + 0.005*"let" + 0.005*"man" + 0.005*"did" + 0.005*"guy" + 0.005*"dude" + 0.004*"come"'),
 (1,
  '0.008*"fuck" + 0.007*"shit" + 0.007*"fucking" + 0.006*"dad" + 0.006*"going" + 0.005*"want" + 0.004*"white" + 0.004*"man" + 0.004*"life" + 0.004*"look"'),
 (2,
  '0.007*"fucking" + 0.006*"went" + 0.006*"day" + 0.006*"thing" + 0.005*"cause" + 0.005*"good" + 0.005*"really" + 0.005*"going" + 0.005*"little" + 0.004*"goes"')]

- this too is not giving enough insights
- let's create a model with 4 topics

In [10]:
# LDA model for 4 topics & 10 passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.006*"love" + 0.006*"shit" + 0.005*"bo" + 0.005*"ok" + 0.005*"want" + 0.005*"stuff" + 0.004*"repeat" + 0.004*"man" + 0.004*"fucking" + 0.004*"lot"'),
 (1,
  '0.011*"fucking" + 0.007*"fuck" + 0.007*"shit" + 0.005*"going" + 0.005*"cause" + 0.005*"want" + 0.005*"thing" + 0.005*"little" + 0.004*"make" + 0.004*"guy"'),
 (2,
  '0.000*"shit" + 0.000*"fuck" + 0.000*"going" + 0.000*"fucking" + 0.000*"little" + 0.000*"day" + 0.000*"did" + 0.000*"thing" + 0.000*"mean" + 0.000*"let"'),
 (3,
  '0.006*"fucking" + 0.006*"good" + 0.006*"shit" + 0.006*"going" + 0.005*"fuck" + 0.005*"day" + 0.005*"went" + 0.005*"thing" + 0.005*"dad" + 0.005*"life"')]

- this too is not giving enough insights
- let's try and modify some other parameters

---
## 2. Topic Modelling: Nouns
- it is a standard practice to create a model on a single part of speech (i.e. only nouns or only adjectives etc.)
- Here we will consider all the nouns for LDA model

In [11]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [12]:
# let us create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

# UDF to tokenize text and extract all nouns
def nouns(text):
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)]
    return " ".join(all_nouns)

In [13]:
# read in the cleaned data
data_clean = pd.read_pickle("clean_corpus.pkl")

data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
bo       bo what old macdonald had a farm e i e i o and...
dave     this is dave he tells dirty jokes for a living...
hasan      whatâs up davis whatâs up iâm home i had to ...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     armed with boyish charm and a sharp wit the fo...
louis    introfade the music out letâs roll hold there ...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [14]:
# apply nouns UDF to clean data
data_noun = pd.DataFrame(data_clean.transcript.apply(nouns))
data_noun

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i â em i francisco city wor...
bill     thank s thank pleasure georgia area oasis t i ...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    â â m home i netflix â la york â i â son davis...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     charm wit â snl â writer john mulaney marriage...
louis    music let â roll hold lights lights thank i t ...
mike     wow hey thanks look insane years everyone i t ...
ricky    hello thank fuck thank welcome i m gon tonight...

In [15]:
# imports for creating a new document term matrix
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# additional stop-words
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people', 'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# create document term matrix
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_noun.transcript)
data_dtm = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtm.index = data_noun.index
data_dtm

,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abortion,abortions,...,ze,zealand,zee,zen,zeppelin,zillion,zombie,zombies,zoo,Ã©clair
ali,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,2,0,...,0,10,0,0,0,0,0,0,0,0
bill,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,1,1,1,0,0
bo,1,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

In [16]:
# create a gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtm.transpose()))

# create a vocabulary dictionary
id2wordn = dict((v,k) for k, v in cvn.vocabulary_.items())

In [17]:
# let's model with 2 stop words
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.009*"life" + 0.009*"thing" + 0.008*"guy" + 0.008*"day" + 0.008*"cause" + 0.007*"don" + 0.007*"gon" + 0.006*"man" + 0.006*"way" + 0.006*"shit"'),
 (1,
  '0.009*"day" + 0.008*"man" + 0.008*"thing" + 0.008*"shit" + 0.008*"gon" + 0.007*"lot" + 0.007*"cause" + 0.007*"fuck" + 0.007*"way" + 0.006*"things"')]

In [18]:
# let's model with 3 stop words
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.010*"dad" + 0.007*"don" + 0.006*"life" + 0.006*"cause" + 0.006*"night" + 0.006*"point" + 0.006*"school" + 0.006*"parents" + 0.006*"way" + 0.005*"girl"'),
 (1,
  '0.012*"shit" + 0.011*"day" + 0.010*"thing" + 0.009*"fuck" + 0.009*"guy" + 0.009*"gon" + 0.009*"man" + 0.008*"lot" + 0.008*"cause" + 0.007*"women"'),
 (2,
  '0.010*"thing" + 0.010*"life" + 0.009*"man" + 0.008*"way" + 0.008*"day" + 0.008*"gon" + 0.008*"cause" + 0.007*"kids" + 0.006*"things" + 0.006*"fuck"')]

In [19]:
# let's model with 4 stop words
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.016*"dad" + 0.008*"life" + 0.007*"mom" + 0.007*"don" + 0.007*"parents" + 0.006*"school" + 0.006*"girl" + 0.006*"home" + 0.006*"hey" + 0.005*"ve"'),
 (1,
  '0.010*"man" + 0.008*"gon" + 0.008*"cause" + 0.008*"day" + 0.007*"way" + 0.007*"shit" + 0.007*"fuck" + 0.007*"lot" + 0.006*"house" + 0.006*"life"'),
 (2,
  '0.014*"thing" + 0.012*"day" + 0.010*"life" + 0.009*"cause" + 0.009*"ve" + 0.007*"guy" + 0.007*"gon" + 0.007*"women" + 0.007*"things" + 0.006*"man"'),
 (3,
  '0.010*"shit" + 0.009*"guy" + 0.009*"gon" + 0.008*"thing" + 0.008*"cause" + 0.008*"day" + 0.007*"man" + 0.007*"way" + 0.007*"fuck" + 0.006*"lot"')]

---
## 3. Topic Modelling: Nouns & Adjectives
- Here we will consider all the nouns & adjectives for LDA model
- fine tune our LDA model

In [23]:
# UDF to tokenize text and extract all nouns & adjectives
def nouns_adj(text):
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    all_nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)]
    return " ".join(all_nouns_adj)

In [24]:
# apply noun-adj UDF 
data_noun_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_noun_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank s thank pleasure greater atlanta g...
bo       old macdonald farm e i i o farm pig e i i snor...
dave     dirty jokes living stare most hard work profou...
hasan    â i â m home i netflix â special la chicago ne...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fuck san francisco thanks...
john     boyish charm sharp wit former â snl â writer j...
louis    music let â roll hold lights lights thank much...
mike     wow hey thanks hey seattle nice look crazy s i...
ricky    hello great thank fuck thank lovely welcome i ...

In [26]:
'''
# imports for creating a new document term matrix
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# additional stop-words
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people', 'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)
'''

# create document term matrix
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_noun_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_noun_adj.index
data_dtmna

,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,able,...,ze,zealand,zee,zen,zeppelin,zillion,zombie,zombies,zoo,Ã©clair
ali,0,0,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
bill,0,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,1,0,0
bo,1,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,1,...,0,0,2,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,1,2,...,0,0,0,0,0,0,0,0,1,0

In [28]:
# create a gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# create a vocabulary dictionary
id2wordna = dict((v,k) for k, v in cvna.vocabulary_.items())

In [29]:
# let's model with 2 stop words
ldana = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.007*"core" + 0.007*"infinite" + 0.007*"ringside" + 0.007*"feathers" + 0.006*"sick" + 0.006*"bushmaster" + 0.006*"gene" + 0.005*"riot" + 0.005*"headshots" + 0.005*"ethnicities"'),
 (1,
  '0.009*"ringside" + 0.009*"core" + 0.008*"photographers" + 0.008*"horrific" + 0.008*"bushmaster" + 0.008*"firewood" + 0.007*"infinite" + 0.007*"feathers" + 0.006*"dancing" + 0.006*"identical"')]

In [30]:
# let's model with 3 stop words
ldana = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.010*"horrific" + 0.009*"bushmaster" + 0.009*"ringside" + 0.007*"sick" + 0.007*"character" + 0.006*"core" + 0.006*"headshots" + 0.006*"feathers" + 0.006*"firewood" + 0.005*"khushi"'),
 (1,
  '0.012*"infinite" + 0.011*"ethnicities" + 0.008*"photographers" + 0.007*"ringside" + 0.007*"firewood" + 0.007*"core" + 0.006*"slow" + 0.006*"sick" + 0.006*"identical" + 0.006*"bushmaster"'),
 (2,
  '0.009*"core" + 0.008*"ringside" + 0.008*"feathers" + 0.007*"photographers" + 0.007*"dancing" + 0.007*"consumers" + 0.007*"bushmaster" + 0.007*"horrific" + 0.006*"separate" + 0.006*"firewood"')]

In [31]:
# let's model with 4 stop words
ldana = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.011*"horrific" + 0.009*"ringside" + 0.008*"core" + 0.008*"infinite" + 0.007*"consumers" + 0.007*"sick" + 0.007*"separate" + 0.006*"dancing" + 0.006*"feathers" + 0.006*"riot"'),
 (1,
  '0.000*"firewood" + 0.000*"photographers" + 0.000*"feathers" + 0.000*"ringside" + 0.000*"core" + 0.000*"horrific" + 0.000*"ethnicities" + 0.000*"bushmaster" + 0.000*"headshot" + 0.000*"infinite"'),
 (2,
  '0.011*"bushmaster" + 0.011*"core" + 0.009*"firewood" + 0.009*"ringside" + 0.007*"slow" + 0.006*"separate" + 0.006*"feathers" + 0.006*"dancing" + 0.006*"sick" + 0.006*"millions"'),
 (3,
  '0.013*"photographers" + 0.009*"feathers" + 0.009*"infinite" + 0.008*"firewood" + 0.007*"bushmaster" + 0.007*"core" + 0.007*"identical" + 0.007*"ethnicities" + 0.007*"ringside" + 0.007*"sick"')]

## 4. Identify Topics in Each Document
- Here we will create a final model with nouns and adjectives and experiment with high passes

In [32]:
# let's model with 4 stop words
ldana = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.012*"benefit" + 0.010*"nude" + 0.008*"rape" + 0.008*"dose" + 0.008*"clit" + 0.007*"infinite" + 0.007*"coffin" + 0.006*"blades" + 0.005*"quick" + 0.005*"pregnant"'),
 (1,
  '0.011*"core" + 0.008*"consumers" + 0.008*"khushi" + 0.008*"hang" + 0.008*"ringside" + 0.008*"character" + 0.007*"sick" + 0.007*"bushmaster" + 0.007*"atari" + 0.006*"paranoid"'),
 (2,
  '0.011*"photographers" + 0.010*"infinite" + 0.008*"ethnicities" + 0.007*"identical" + 0.006*"aframe" + 0.005*"kim" + 0.005*"operator" + 0.005*"firewood" + 0.005*"slow" + 0.005*"slip"'),
 (3,
  '0.010*"ringside" + 0.009*"core" + 0.009*"feathers" + 0.009*"horrific" + 0.009*"bushmaster" + 0.008*"photographers" + 0.008*"firewood" + 0.008*"infinite" + 0.007*"ethnicities" + 0.007*"dancing"')]

Identifying the 4 models
1. Topic 0: profanity and sexuality
2. Topic 1: emotions
3. Topic 2: objects
4. Topic 3: events

In [44]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a for a in corpus_transformed], data_dtmna.index))

[([(0, 0.103940286), (1, 0.14412665), (2, 0.10409819), (3, 0.64783484)],
  'ali'),
 ([(0, 0.14821835), (1, 0.20780604), (2, 0.065512225), (3, 0.5784634)],
  'anthony'),
 ([(0, 0.1336029), (1, 0.17372632), (2, 0.08002505), (3, 0.6126457)], 'bill'),
 ([(0, 0.12993217), (1, 0.16847838), (2, 0.07316212), (3, 0.6284274)], 'bo'),
 ([(0, 0.105054855), (1, 0.1734286), (2, 0.09470527), (3, 0.62681127)],
  'dave'),
 ([(0, 0.07818512), (1, 0.1327857), (2, 0.08631908), (3, 0.7027101)], 'hasan'),
 ([(0, 0.0907167), (1, 0.22075741), (2, 0.09775512), (3, 0.5907708)], 'jim'),
 ([(0, 0.11451757), (1, 0.15494406), (2, 0.06358708), (3, 0.6669513)], 'joe'),
 ([(0, 0.06804842), (1, 0.19236064), (2, 0.12254468), (3, 0.6170463)], 'john'),
 ([(0, 0.09122375), (1, 0.130735), (2, 0.10495118), (3, 0.67309016)], 'louis'),
 ([(0, 0.11037963), (1, 0.14720242), (2, 0.094000176), (3, 0.6484178)],
  'mike'),
 ([(0, 0.1190894), (1, 0.13103256), (2, 0.104158625), (3, 0.6457194)],
  'ricky')]

- all comedy special transcripts are a mix of different topics